// Package testmodel writes a minimal, structurally complete, deterministic
// GGUF that GopherLLM can load and run a real (if meaningless) generation
// against, so tests of the embedding surfaces (mobile, the C ABI and the
// Rust, Python and Swift bindings built on it) exercise a real model without
// a binary .gguf in the repository. cmd/gopherllm-synth-testmodel exposes it
// on the command line for the non-Go test suites.
//
// It is the tiny 1-layer "llama"-architecture shape validated by
// TestGGUFWriterRoundTrip and server/synthgguf_test.go's buildTinyLlamaGGUF,
// written through the production gopherllm.NewGGUFWriter API, with a fixed
// pseudo-random weight seed chosen so generation deterministically produces
// printable ASCII text instead of the byte-garbage a truly random tiny model
// tends toward. Changing any weight changes the expected text the binding
// tests assert.
package testmodel

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"os"

	gopherllm "github.com/SimonWaldherr/GopherLLM"
)

type namedTensor struct {
	plan gopherllm.PlannedTensor
	data []byte
}

// Name is the general.name the fixture declares.
const Name = "gopherllm-synth-testmodel"

const (
	dim           = 16
	heads         = 2
	kv            = 2
	headDim       = dim / heads // 8
	hiddenFFN     = 32
	contextLength = 256
	weightSeed    = 3
)

// vocab is <unk>/<s>/</s> followed by every printable ASCII character
// (space through '~'), so any realistic test prompt tokenizes cleanly and
// every generated byte is trivially valid UTF-8 -- unlike a byte-fallback
// vocabulary, there is no way for this model to emit an incomplete rune.
func vocab() []string {
	toks := []string{"<unk>", "<s>", "</s>"}
	for c := ' '; c <= '~'; c++ {
		toks = append(toks, string(rune(c)))
	}
	return toks
}

func smallWeights(n, seed int) []float32 {
	out := make([]float32, n)
	for i := range out {
		out[i] = float32(((i+seed)%13)-6) / 20
	}
	return out
}

func onesF32(n int) []float32 {
	out := make([]float32, n)
	for i := range out {
		out[i] = 1
	}
	return out
}

func f32Bytes(f []float32) []byte {
	b := make([]byte, 4*len(f))
	for i, v := range f {
		binary.LittleEndian.PutUint32(b[i*4:], math.Float32bits(v))
	}
	return b
}

// WriteFile writes the fixture to path.
func WriteFile(path string) error {
	toks := vocab()
	scores := make([]float32, len(toks))

	metadata := map[string]gopherllm.MetaValue{
		"general.architecture":                   {Kind: "str", Value: "llama"},
		"general.name":                           {Kind: "str", Value: Name},
		"llama.embedding_length":                 {Kind: "u32", Value: uint32(dim)},
		"llama.block_count":                      {Kind: "u32", Value: uint32(1)},
		"llama.attention.head_count":             {Kind: "u32", Value: uint32(heads)},
		"llama.attention.head_count_kv":          {Kind: "u32", Value: uint32(kv)},
		"llama.attention.key_length":             {Kind: "u32", Value: uint32(headDim)},
		"llama.attention.value_length":           {Kind: "u32", Value: uint32(headDim)},
		"llama.feed_forward_length":              {Kind: "u32", Value: uint32(hiddenFFN)},
		"llama.context_length":                   {Kind: "u32", Value: uint32(contextLength)},
		"llama.attention.layer_norm_rms_epsilon": {Kind: "f32", Value: float32(1e-5)},
		"llama.rope.freq_base":                   {Kind: "f32", Value: float32(10000)},
		"llama.rope.dimension_count":             {Kind: "u32", Value: uint32(headDim)},
		"tokenizer.ggml.model":                   {Kind: "str", Value: "llama"},
		"tokenizer.ggml.tokens":                  {Kind: "array", Value: toks},
		"tokenizer.ggml.scores":                  {Kind: "array", Value: scores},
		"tokenizer.ggml.bos_token_id":            {Kind: "u32", Value: uint32(1)},
		"tokenizer.ggml.eos_token_id":            {Kind: "u32", Value: uint32(2)},
		"tokenizer.ggml.add_bos_token":           {Kind: "bool", Value: true},
	}

	f32t := func(name string, rows, cols, seed int) (gopherllm.PlannedTensor, []byte) {
		return gopherllm.PlannedTensor{Name: name, Dims: []uint64{uint64(cols), uint64(rows)}, DType: gopherllm.GGMLTypeF32},
			f32Bytes(smallWeights(rows*cols, seed))
	}
	vec := func(name string, n int) (gopherllm.PlannedTensor, []byte) {
		return gopherllm.PlannedTensor{Name: name, Dims: []uint64{uint64(n)}, DType: gopherllm.GGMLTypeF32},
			f32Bytes(onesF32(n))
	}

	add := func(list []namedTensor, plan gopherllm.PlannedTensor, data []byte) []namedTensor {
		return append(list, namedTensor{plan, data})
	}

	var tensors []namedTensor
	p, d := f32t("token_embd.weight", len(toks), dim, weightSeed+1)
	tensors = add(tensors, p, d)
	p, d = vec("output_norm.weight", dim)
	tensors = add(tensors, p, d)
	p, d = f32t("output.weight", len(toks), dim, weightSeed+2)
	tensors = add(tensors, p, d)
	p, d = vec("blk.0.attn_norm.weight", dim)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.attn_q.weight", heads*headDim, dim, weightSeed+3)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.attn_k.weight", kv*headDim, dim, weightSeed+4)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.attn_v.weight", kv*headDim, dim, weightSeed+5)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.attn_output.weight", dim, heads*headDim, weightSeed+6)
	tensors = add(tensors, p, d)
	p, d = vec("blk.0.ffn_norm.weight", dim)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.ffn_gate.weight", hiddenFFN, dim, weightSeed+7)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.ffn_up.weight", hiddenFFN, dim, weightSeed+8)
	tensors = add(tensors, p, d)
	p, d = f32t("blk.0.ffn_down.weight", dim, hiddenFFN, weightSeed+9)
	tensors = add(tensors, p, d)

	planned := make([]gopherllm.PlannedTensor, len(tensors))
	for i, t := range tensors {
		planned[i] = t.plan
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	if err := write(f, metadata, planned, tensors); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

func write(w io.Writer, metadata map[string]gopherllm.MetaValue, planned []gopherllm.PlannedTensor, tensors []namedTensor) error {
	gw, err := gopherllm.NewGGUFWriter(w, metadata, planned, 32)
	if err != nil {
		return fmt.Errorf("NewGGUFWriter: %w", err)
	}
	for _, t := range tensors {
		if err := gw.WriteTensor(t.data); err != nil {
			return fmt.Errorf("WriteTensor(%s): %w", t.plan.Name, err)
		}
	}
	return gw.Close()
}
