#!/usr/bin/env python3
"""Generate dependency-free canonical normalization data from Python Unicode."""
import pathlib
import unicodedata as u
root = pathlib.Path(__file__).resolve().parents[1]
p = root / 'internal/tokenizer/nfc_tables.go'
decomp, ccc, compose = [], [], []
for cp in range(0x110000):
    if 0xAC00 <= cp < 0xAC00 + 11172:  # Hangul is handled algorithmically.
        continue
    ch = chr(cp)
    if u.combining(ch): ccc.append(f'{cp:x}:{u.combining(ch):x}')
    d = u.decomposition(ch)
    if d and not d.startswith('<'):
        seq = [int(x, 16) for x in d.split()]
        decomp.append(f'{cp:x}:' + ','.join(f'{x:x}' for x in seq))
        if len(seq) == 2 and u.normalize('NFC', ''.join(map(chr, seq))) == ch:
            compose.append(f'{seq[0]:x},{seq[1]:x}:{cp:x}')
with p.open('w') as f:
    f.write('// Code generated by scripts/generate_unicode_nfc.py; DO NOT EDIT.\n')
    f.write(f'// Unicode {u.unidata_version}.\npackage tokenizer\n\n')
    for name, rows in [('nfcDecompositions', decomp), ('nfcClasses', ccc), ('nfcCompositions', compose)]:
        f.write(f'const {name} = `'+ ' '.join(rows) +'`\n\n')
